{-# LANGUAGE ViewPatterns, ScopedTypeVariables, RankNTypes, ApplicativeDo,
    DerivingStrategies, DeriveAnyClass, DeriveGeneric #-}

-- Analysis of Problem 208. (all angles are degrees)
--
-- Write c = cos(36) and s = sin(36). For now, treat these strictly as
-- symbolic variables (we will simplify them later).
--
-- The only directions the robot can face are multiples of 72. And
-- some straightforward trigonometry tells us that if the robot is
-- facing at angle α, then the directions the robot can move are α ±
-- 36. So all angles relevant to this problem are multiples of 36.
--
-- The robot's state is a 3-tuple (d, x, y). d is the direction (in
-- multiples of 72, so there are five options), and x and y are the
-- coordinates.
--
-- Assume the robot starts at (0, 0, 0). Then a "move" involves moving
-- the robot in a legal direction, which adds cos(36N) to x and
-- sin(36N) to y (where N is determined by the direction of motion).
--
-- Through some elbow grease and Paul Dawkins' wonderful trig
-- reference
-- (https://tutorial.math.lamar.edu/pdf/Trig_Cheat_Sheet_Reduced.pdf),
-- we enumerate the possible values of these expressions below.
--
-- cos(0) = 1
-- cos(36) = c
-- cos(72) = 2 c^2 - 1
-- cos(108) = 1 - 2 c^2
-- cos(144) = - c
-- cos(180) = - 1
-- cos(216) = - c
-- cos(252) = 1 - 2 c^2
-- cos(288) = 2 c^2 - 1
-- cos(324) = c
--
-- sin(0) = 0
-- sin(36) = s
-- sin(72) = 2 s c
-- sin(108) = 2 s c
-- sin(144) = s
-- sin(180) = 0
-- sin(216) = - s
-- sin(252) = - 2 s c
-- sin(288) = - 2 s c
-- sin(324) = - s
--
-- Observations: Every one of these is a polynomial in 1, c, c^2, s,
-- and s c. And we only ever add linear multiples of these, so we're
-- working in some module over Z. Now let's get some real values for
-- these numbers. WolframAlpha tells us that
--
-- c = cos(36) = 1/4 + sqrt(5)/4
--
-- s = sin(36) = 1/2 * sqrt(1/2 * (5 - sqrt(5)))
--
-- Let's start with the s. I never square an s, so it's only used
-- linearly. No other term here has a square root with anything
-- resembling that radical (to be precise, that radical is likely an
-- extension of degree 4 over Q, where the only other radical is
-- sqrt(5) which clearly has degree 2). So in a polynomial with these
-- terms, all of the s and s c^2 terms must be zero in order for the
-- polynomial to be zero.
--
-- c is a bit more complicated. Forgetting about s for a minute, we're
-- looking at the space generated by {1, c, c^2}, which is three
-- elements and we know that a basis of this space is {1, sqrt(5)} (so
-- the module has length 2). So there must be linear dependence in {1,
-- c, c^2}. A bit of linear algebra gives us that this linear
-- independence can be expressed as 0 = 1 + 2 c - 4 c^2. Module theory
-- tells us that (up to linear multiples) this is the only nontrivial
-- formula in these three variables. Hence, 1 = 4 c^2 - 2 c.
-- Substituting this into the above formulas gives us a new table.
--
-- cos(0) = 4 c^2 - 2 c
-- cos(36) = c
-- cos(72) = 2 c - 2 c^2
-- cos(108) = 2 c^2 - 2 c
-- cos(144) = - c
-- cos(180) = - 4 c^2 + 2 c
-- cos(216) = - c
-- cos(252) = 2 c^2 - 2 c
-- cos(288) = 2 c - 2 c^2
-- cos(324) = c
--
-- sin(0) = 0
-- sin(36) = s
-- sin(72) = 2 s c
-- sin(108) = 2 s c
-- sin(144) = s
-- sin(180) = 0
-- sin(216) = - s
-- sin(252) = - 2 s c
-- sin(288) = - 2 s c
-- sin(324) = - s
--
-- This fully represents a free Z-module of length 4 with basis {c,
-- c^2, s, s c}.
--
-- Runs in about 13 seconds. GHC optimizations do not appear to help
-- or hinder.

import Data.List
import Data.Maybe
import Data.Hashable (Hashable)
import Data.HashMap.Strict (HashMap)
import qualified Data.HashMap.Strict as HashMap
import Control.Monad.State
import GHC.Generics

import Debug.Trace

data ZModule = ZModule Integer Integer Integer Integer
               deriving stock (Eq, Generic)
               deriving anyclass Hashable

cTerm :: ZModule -> Integer
cTerm (ZModule c _ _ _) = c

c2Term :: ZModule -> Integer
c2Term (ZModule _ c2 _ _) = c2

sTerm :: ZModule -> Integer
sTerm (ZModule _ _ s _) = s

scTerm :: ZModule -> Integer
scTerm (ZModule _ _ _ sc) = sc

instance Show ZModule where
    showsPrec _ (ZModule 0 0 0 0) = ("0" ++)
    showsPrec _ (ZModule c c2 s sc) = foldr (.) id . intersperse (" + " ++) $ mapMaybe term [(c, "c"), (c2, "c^2"), (s, "s"), (sc, "s c")]
        where term (0, _) = Nothing
              term (n, s) = Just (shows n . showString " " . showString s)

-- Half-baked impl mainly to get fromInteger (but also (+) is nice)
instance Num ZModule where
    ZModule c c2 s sc + ZModule c' c2' s' sc' = ZModule (c + c') (c2 + c2') (s + s') (sc + sc')
    negate (ZModule c c2 s sc) = ZModule (-c) (-c2) (-s) (-sc)
    (*) = error "Unimplemented (*)"
    abs = error "Unimplemented abs"
    signum = error "Unimplemented signum"
    fromInteger n = n .* one

one :: ZModule
one = ZModule (-2) 4 0 0

(.*) :: Integer -> ZModule -> ZModule
n .* (ZModule c c2 s sc) = ZModule (c * n) (c2 * n) (s * n) (sc * n)

data RobotPosition = RobotPosition {
      robotDir :: Int, -- 0 to 4 inclusive.
      robotX :: ZModule,
      robotY :: ZModule
    }
    deriving stock (Show, Eq, Generic)
    deriving anyclass (Hashable)

instance Semigroup RobotPosition where
    RobotPosition d x y <> RobotPosition d' x' y' = RobotPosition ((d + d') `mod` 5) (x + x') (y + y')

instance Monoid RobotPosition where
    mempty = startPosition

-- NOTE: I start the robot facing east just because it made the trig
-- simpler when I was drawing the diagram. No other differences, since
-- it's just a 90 degree rotation of the whole problem. We are working
-- in mathematical coordinates, so positive Y is up and
-- "counterclockwise" means "positive angle".
startPosition :: RobotPosition
startPosition = RobotPosition 0 0 0

data Move = Clockwise | Anticlockwise
            deriving (Show, Read, Eq, Ord, Enum, Bounded)

-- From the table above
cos36n :: Int -> ZModule
cos36n 0 = ZModule (-2) 4 0 0
cos36n 1 = ZModule 1 0 0 0
cos36n 2 = ZModule 2 (-2) 0 0
cos36n 3 = ZModule (-2) 2 0 0
cos36n 4 = ZModule (-1) 0 0 0
cos36n 5 = ZModule 2 (-4) 0 0
cos36n 6 = ZModule (-1) 0 0 0
cos36n 7 = ZModule (-2) 2 0 0
cos36n 8 = ZModule 2 (-2) 0 0
cos36n 9 = ZModule 1 0 0 0
cos36n _ = undefined

-- From the table above
sin36n :: Int -> ZModule
sin36n 0 = ZModule 0 0 0 0
sin36n 1 = ZModule 0 0 1 0
sin36n 2 = ZModule 0 0 0 2
sin36n 3 = ZModule 0 0 0 2
sin36n 4 = ZModule 0 0 1 0
sin36n 5 = ZModule 0 0 0 0
sin36n 6 = ZModule 0 0 (-1) 0
sin36n 7 = ZModule 0 0 0 (-2)
sin36n 8 = ZModule 0 0 0 (-2)
sin36n 9 = ZModule 0 0 (-1) 0
sin36n _ = undefined

moveToAction :: RobotPosition -> Move -> RobotPosition
moveToAction (robotDir -> dir) move = RobotPosition dir' (cos36n moveDir) (sin36n moveDir)
    where dir' = case move of
                   Clockwise -> 4
                   Anticlockwise -> 1
          moveDir = case move of
                      Clockwise -> (2 * dir - 1) `mod` 10
                      Anticlockwise -> (2 * dir + 1) `mod` 10

applyMove :: Move -> RobotPosition -> RobotPosition
applyMove move robot = robot <> moveToAction robot move

applyMoves :: RobotPosition -> [Move] -> RobotPosition
applyMoves = foldl' (flip applyMove)

applyMovesToStart :: [Move] -> RobotPosition
applyMovesToStart = applyMoves startPosition

-- The problem description does not make it clear whether or not "back
-- at the start position" means it must be facing the correct
-- direction too. I may change this definition later. I'm assuming
-- "yes" for now.
--
-- As far as I can tell, the two definitions are equivalent for our
-- purposes, which is fascinating.
isStartPosition :: RobotPosition -> Bool
isStartPosition = (== startPosition)

-- General purpose memoization of a single function argument.
memo :: forall a b. (Show a, Show b, Hashable a) => (forall m. Applicative m => (a -> m b) -> a -> m b) -> a -> State (HashMap a b) b
memo f = f'
    where f' :: Hashable a => a -> State (HashMap a b) b
          f' a = do
            m <- get
            case HashMap.lookup a m of
              Just b -> pure b
              Nothing -> do
                   b <- f f' a
                   modify $ HashMap.insert a b
                   return b

-- Making sure the memoization works with a simple Fibonacci function.
fiboF :: Applicative m => (Integer -> m Integer) -> Integer -> m Integer
fiboF _ 0 = pure 0
fiboF _ 1 = pure 1
fiboF f n = (+) <$> f (n - 1) <*> f (n - 2)

fibo :: Integer -> Integer
fibo = flip evalState mempty . memo fiboF

-- The real thing
type CountPathsInput = (RobotPosition, Int)

countPathsF :: Applicative m => (CountPathsInput -> m Integer) -> CountPathsInput -> m Integer
countPathsF _ (pos, 0) = if isStartPosition pos then pure 1 else pure 0
countPathsF f (pos, n) = do
  clockwise <- f (applyMove Clockwise pos, n - 1)
  anticlockwise <- f (applyMove Anticlockwise pos, n - 1)
  return $ clockwise + anticlockwise

countPaths :: Int -> Integer
countPaths n = memoized (startPosition, n)
    where memoized = flip evalState mempty . memo countPathsF

main :: IO ()
main = do
  --print $ countPaths 25
  print $ countPaths 70
{-
  print $ fibo 1000
  print startPosition
  print $ applyMovesToStart [Anticlockwise, Clockwise, Clockwise, Anticlockwise]
  print $ applyMovesToStart [Clockwise, Anticlockwise, Anticlockwise, Clockwise]
  -- The diagram from the problem text
  print $ applyMovesToStart [Anticlockwise, Clockwise, Anticlockwise, Anticlockwise, Anticlockwise, Clockwise, Clockwise, Clockwise, Clockwise, Anticlockwise, Clockwise, Clockwise, Anticlockwise, Clockwise, Anticlockwise, Anticlockwise, Anticlockwise, Anticlockwise, Clockwise, Anticlockwise, Anticlockwise, Clockwise, Anticlockwise, Anticlockwise, Anticlockwise]
-}
